### ISSUE TITLE
Icons Do Not Display on Production Build

### ISSUE THREAD

**Issue by unixneo** [kadinzhang/Periodicity#2]
@kadinzhang

Hi Kadin Zhang,

Nice view project indeed!

When I install and run Periodicity on the desktop in development mode, it works great; but when I build it and deploy to a web server, a number of icons do not display (menu, open_in_new, poll, library_add and more).  See image below:

![screen shot 2018-11-25 at 7 22 42 pm](https://user-images.githubusercontent.com/12891828/48979116-bf751380-f0e8-11e8-96c8-df3be3cad11d.png)

I have tried multiple builds from scratch (npm run build) and have also tried your production build in this repo and nothing clears this error.

Can you please tell me how to fix this problem?

Thanks.

**Comment by kadinzhang** [comment]
Since the icons are not rendering, the problem is probably with the <v-icon> in PeriodicTable.vue. I would look into perhaps a css conflict with the `Material Icons` font family that is responsible for the icons, as it looks like they are rendering in `Open Sans`.

If you can't resolve the issue, let me know all the steps you took to build and deploy the app to a web server from the current build so I can help you further.

**Comment by unixneo** [comment]
Update,  I got it to work on my production web server by adding this bandaid fix to index.html


```
<link href="https://fonts.googleapis.com/css?family=Material+Icons" rel="stylesheet">
```

You should probably update your code so adding this is not necessary.

**Comment by unixneo** [comment]
It seems that this line is not importing property when building for production:

File:  PeriodicTable.vue

```
import 'material-design-icons-iconfont/dist/material-design-icons.css'
```

**Comment by unixneo** [comment]
FYI... devtools confirm that on your production build these Material fonts are not loading, FYI; so then it fallsback to the CSS file which I added to index.html.

For what it's worth ...

**Comment by unixneo** [comment]
Not sure if I'll dive in to fully fix it, as I was just installing your excellent periodic table to see how easy it was to get it running on our production server.   It's not really necessary for us and it's not germane to our site, so I just put up a link to your example site at: 

https://periodicity.io/ 

By sharing with our forum members in a post here:

https://www.unix.com/what-is-on-your-mind-/280397-vuejs-periodic-table-kadin-zhang.html

Looking forward to seeing more of your artistic Vue.js examples where you combine science with art!

**Comment by kadinzhang** [comment]
Got it. Thanks for checking out the site!
