### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by diomed** [kadinzhang/Periodicity#3]
is translation / localization possible?
what would I need to edit?

**Comment by kadinzhang** [comment]
It's probably possible with [Transifex](https://www.transifex.com/vuejs/vue-cli/), by adding a locales/ folder. Is that what you're looking for?

**Comment by diomed** [comment]
could you tell me which files exactly should I look for?

**Comment by diomed** [comment]
I see now that it's Periodic-Table-JSON that I wanna translate. 
Thanks.
