### ISSUE TITLE
Motivation for periodicity

### ISSUE THREAD

**Issue by zhongjingjogy** [kadinzhang/Periodicity#5]
Hi Kadin,

I would like to say that Periodicity is a very delicate and nice product. I wonder what the initiative is for elaborating such a beautiful piece.

Sincerely,

Jing

**Comment by zhongjingjogy** [comment]
That is great! I really appreciate your work and your time! My curiosity has been satisfied.

Best regards!

**Comment by kadinzhang** [comment]
Thanks! It would be great to know my project can help out chemistry students! 😄
